// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw9CGtO0gDx64YtE_V3nzdYldqBj4q2W0',
    appId: '1:335706305683:web:ccdae707b5591adf734966',
    messagingSenderId: '335706305683',
    projectId: 'muslim-pro-66652',
    authDomain: 'muslim-pro-66652.firebaseapp.com',
    storageBucket: 'muslim-pro-66652.firebasestorage.app',
    measurementId: 'G-LRYQ8MK6K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0fL0DCl7hJp_cbv6LuV4pxhj2XileIJI',
    appId: '1:335706305683:android:d6058bdcfba1cab7734966',
    messagingSenderId: '335706305683',
    projectId: 'muslim-pro-66652',
    storageBucket: 'muslim-pro-66652.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Nd_hPUB3MoBhxx8t85nKof4_WE9fxvQ',
    appId: '1:335706305683:ios:4a2fd1f8edb21623734966',
    messagingSenderId: '335706305683',
    projectId: 'muslim-pro-66652',
    storageBucket: 'muslim-pro-66652.firebasestorage.app',
    iosBundleId: 'com.example.muslimPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Nd_hPUB3MoBhxx8t85nKof4_WE9fxvQ',
    appId: '1:335706305683:ios:4a2fd1f8edb21623734966',
    messagingSenderId: '335706305683',
    projectId: 'muslim-pro-66652',
    storageBucket: 'muslim-pro-66652.firebasestorage.app',
    iosBundleId: 'com.example.muslimPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw9CGtO0gDx64YtE_V3nzdYldqBj4q2W0',
    appId: '1:335706305683:web:a4a2137762233707734966',
    messagingSenderId: '335706305683',
    projectId: 'muslim-pro-66652',
    authDomain: 'muslim-pro-66652.firebaseapp.com',
    storageBucket: 'muslim-pro-66652.firebasestorage.app',
    measurementId: 'G-1F9R1ZX4W4',
  );

}